### ISSUE TITLE
R-devel build failing

### ISSUE THREAD

**Issue by pat-s** [s-u/R-mac-dev#3]
Disclaimer: I saw the post in the mailing list by Jim some days ago.

Since I prefer this platform over mailing lists, a follow-up here: There seems to be an issue with latex: https://mac.r-project.org/log-R-devel.high-sierra.x86_64.html

**Comment by s-u** [comment]
Thanks, apparently the cron job didn't have TeX on its `PATH`. I was running it manually before so it was on the `PATH`. Now hopefully fixed in r4296 - we'll see tonight.
